>XX;5fd1
5fd1 - 5fd1
AFVVTDNCIKCKYTDCVEVCPVDCFYEGPNFLVIHPDECIDCALCEPECPAQAIFSEDEV
PEDMQEFIQLNAELAEVWPNITEKKDPLPDAEDWDGVKGKLQHLER*
>XX;1fdx
1fdx - 1fdx
AYVINDSCIACGACKPECPVNIIQGS--IYAIDADSCIDCGSCASVCPVGAPNPED----
--------------------------------------------*
